import asyncio
import hashlib

# from .messages import send_message
import importlib
import logging
import os
import re
import uuid
from dataclasses import dataclass
from glob import glob
from typing import Final, List, Optional, Tuple

import httpx
import pandas as pd
import sentry_sdk
from PIL import Image
from pydantic import ValidationError
from sqlalchemy import func
from sqlalchemy.orm.attributes import flag_modified
from sqlmodel import Session, col, delete, select
from typing_extensions import deprecated

from .chat_models import MessageType as ChatMessageType
from .chat_types import MessageDTO, MessageType
from .config import config
from .content_models import (
    DirectusFile,
    ImageInfo,
    ImagesUserSettings,
    LLMStats,
    UserImageView,
)
from .llm_services.api import LLMServiceAPI
from .llm_services.schemes import ImageCaptionResponse

logger = logging.getLogger(__name__)

if os.environ.get("TEST_ENV") != "ci":
    from dotenv import load_dotenv

    load_dotenv()


def _get_exif_data(image_path):
    image = Image.open(image_path)
    exif_data = image._getexif()

    return image.info["parameters"]


def get_meta_from_image(img_path: str, char_name_id_map) -> ImageInfo:
    full_path = os.path.abspath(img_path)  # replace for the image url later
    filename = os.path.basename(img_path)
    imgname = filename.split("/")[-1]
    desc = ".".join(imgname.split(".")[:-1]).lower()

    desc = desc.replace("img/", "")
    desc = desc.replace(".json", "")
    desc = desc.replace("_description", "")
    img_parts = desc.split(" + ")

    # replace \d+ with a regex
    img_parts = [re.sub(r"\d+_", "", part) for part in img_parts]
    char_name = img_parts[0]
    location = img_parts[1].replace("_", " ")
    cloths = img_parts[2].replace("_", " ")

    last_parts = img_parts[3].split("_")

    if "rating" not in last_parts:
        last_parts.insert(0, "rating")

    rating = " ".join(last_parts[:2]).replace("rating", "").strip()
    behavior = " ".join(last_parts[2:4]).replace("behavior", "").strip()
    exif = _get_exif_data(img_path)
    prompt = exif.split("\n")[0]

    with open(full_path, "rb") as f:
        hash = hashlib.file_digest(f, "sha256")

    digest = hash.hexdigest()
    if digest is None:
        raise ValueError("Digest is None")
    result = ImageInfo(
        hash=digest,
        path="file://" + full_path,
        character=char_name_id_map[char_name],
        location=location,
        cloths=cloths,
        rating=rating,
        behavior=behavior,
        prompt=prompt,
        name=imgname,
        char_name=char_name,
    )

    result.hash = digest
    logger.debug(f"Image: {img_path} => {result.model_dump()}")
    return result


@deprecated("New upload pipeline is not implemented yet")
def _magic_copy(detached_model: ImageInfo, attached_model: ImageInfo):
    detached_model_dict = detached_model.model_dump(
        exclude={"id"}
    )  # Exclude the ID if it's not to be updated
    for key, value in detached_model_dict.items():
        setattr(attached_model, key, value)


@deprecated("New upload pipeline is not implemented yet")
def _save_image_batch(session: Session, batch: List[ImageInfo]) -> Tuple[int, int]:
    # ids in the batch are autogenerated and thus incorrect for updates!
    batch_map_hash = {i.hash: i for i in batch}
    batch_map_ids = {i.id: i for i in batch}
    hashes_to_check = list(map(lambda i: i.hash, batch))

    stmt = select(ImageInfo).where(col(ImageInfo.hash).in_(hashes_to_check))
    existing_imgs = session.exec(stmt).all()

    ids_for_update = list(map(lambda i: i.id.hex, existing_imgs))
    hashes_for_update = list(map(lambda i: i.hash, existing_imgs))

    hashes_for_insert = list(filter(lambda i: i not in hashes_for_update, batch_map_hash))

    for i in hashes_for_insert:
        session.add(batch_map_hash[i])

    imgs_to_update = []
    for i in existing_imgs:
        tmp_id = i.id
        _magic_copy(batch_map_hash[i.hash], i)
        i.id = tmp_id
        imgs_to_update.append(i)

    for i in ids_for_update:
        session.add_all(imgs_to_update)

    return len(hashes_for_insert), len(ids_for_update)


@deprecated("New upload pipeline is not implemented yet")
def add_images_from_folder(session, folder: str) -> Tuple[int, int]:
    BATCH_SIZE = 10
    i = 0
    everything = []
    current_batch: List[ImageInfo] = []
    counters = (0, 0)
    for image_path in glob(os.path.join(folder, "**")):
        image_info = get_meta_from_image(image_path)
        current_batch.append(image_info)
        if i == BATCH_SIZE - 1:
            inserted, updated = _save_image_batch(session, current_batch)
            counters = (counters[0] + inserted, counters[1] + updated)
            current_batch = []
        i += 1
        everything.append(image_info)
    if len(current_batch) > 0:
        inserted, updated = _save_image_batch(session, current_batch)  # last batch
        counters = (counters[0] + inserted, counters[1] + updated)
    return counters


# WARN Sensitive to changes
IMAGE_TYPES: Final[list[str]] = ["safe", "questionable", "nude", "explicit"]


class AllImagesAreShownException(Exception): ...


class NoImagesException(Exception): ...


def get_next_image(
    session: Session,
    user_id: uuid.UUID,
    char_id: int,
    requested_image_type: str = "safe",
    requested_location: str = "private massage room",
    config_id: Optional[uuid.UUID] = None,
) -> ImageInfo:
    """1. The purpose of get_next_image is to send a message to the user with an attachment containing an image of the desired type (Photo, Sensual, Sexy, Hot).

    2. There are several restrictions on what kind of picture it is:
    - Pictures should not be repeated (there is a separate table in the database where users' views of images are recorded).
    - In this regard, we cannot expect that there will always be a Sexy type of picture, there may be a situation when all images of this type have been viewed.
    - To handle such a situation, pictures should be given either of this type or of the less erotic type. Hot → Sexy → Sensual → Photo → No more unseen pictures.
    3. So that the user does not have different things flashing before his eyes, we must give out pictures of the same type, grouped by clothes (the Wear field), because such pictures are similar.
    4. So the algorithm of the issue is something like this:
    ---
    1. the user asked for a picture <type=sexy>
    2. Does the user have unseen images of the <type> type? if not, do <type=type-1> (for sexy it is sensual) and repeat first (1). if yes, go ahead.
    3. Does the user have a mark in the settings that he started looking at specific clothes of the <type> type? if so, then go ahead. if not, then we are looking for which types of clothes <wear> for the type <type> are more overlooked, write them down in the settings, go further.
    4. from the remaining unseen photos of the type <type> with <wear>, select a random one. If there are none, we remove the clothes from the settings, and go to (3)
    5. we send it to the user
    6. after sending, we mark it as viewed

    Args:
        session (Session): Sqlmodel session
        user_id (uuid.UUID): user id
        char_id (int): character id
        requested_image_type (str, optional): image type. Defaults to "safe".
        requested_location (str, optional): location(not in use). Defaults to "private massage room".

    Raises:
        NoImagesException: Unexpected error
        AllImagesAreShownException: Expected error if user saw all images
        Exception: _description_

    Returns:
        ImageInfo: Image db object
    """
    if requested_image_type not in IMAGE_TYPES:
        requested_image_type = "safe"

    user_settings = session.get(ImagesUserSettings, user_id)

    if not user_settings:
        user_settings = ImagesUserSettings(id=user_id)
        session.add(user_settings)
        logger.debug(f"No settings")
    else:
        logger.debug(f"User settings: {user_settings.settings}")

    SETTINGS_IMAGE_CLOTHES_TYPE_KEY = "image_clothes_type_map_{image_type}" + f"_{char_id}"

    key_image_clothes_type_from_settings = SETTINGS_IMAGE_CLOTHES_TYPE_KEY.format(
        image_type=requested_image_type
    )

    # Subquery to find image_ids already viewed by the user
    user_viewed_images_subquery = select(UserImageView.image_id).where(
        UserImageView.user_id == user_id
    )
    image_type = requested_image_type

    # Select the image based on the conditions and group by the cloths field, selecting the largest group
    next_image_subquery = (
        select(ImageInfo.cloths, func.count(ImageInfo.id).label("photo_count"))
        .where(
            ImageInfo.id.not_in(user_viewed_images_subquery),
            ImageInfo.rating == image_type,
            ImageInfo.character == char_id,
            ImageInfo.is_free == False,
            ImageInfo.config_id == config_id,
        )
        .group_by(ImageInfo.cloths)
        .order_by(func.count(ImageInfo.id).desc())
        .limit(1)
    )

    # check if settings already have a mapping for the required cloth
    if key_image_clothes_type_from_settings in user_settings.settings:
        clothes_type: str = user_settings.settings[key_image_clothes_type_from_settings]

        # Main query to get images not viewed by the user
        next_image_stmt = (
            select(ImageInfo)
            .where(
                ImageInfo.character == char_id,
                ImageInfo.rating == image_type,
                ImageInfo.cloths == clothes_type,
                ImageInfo.is_free == False,
                ImageInfo.config_id == config_id,
                ImageInfo.id.not_in(user_viewed_images_subquery),
            )
            .order_by(func.random())
            .limit(1)
        )
    else:
        clothes_type = session.exec(next_image_subquery).first()
        if clothes_type:
            clothes_type = clothes_type[0]

        # Main query to get images not viewed by the user
        next_image_stmt = (
            select(ImageInfo)
            .where(
                ImageInfo.character == char_id,
                ImageInfo.rating == image_type,
                ImageInfo.cloths == next_image_subquery.c.cloths,
                ImageInfo.is_free == False,
                ImageInfo.id.not_in(user_viewed_images_subquery),
                ImageInfo.config_id == config_id,
            )
            .order_by(func.random())
            .limit(1)
        )

    next_cloths_result = None
    # If we don't have clothes type it is mean that all images at this cloths category is viewed and we don't need to execute main query
    if clothes_type:
        user_settings.settings[key_image_clothes_type_from_settings] = clothes_type
        flag_modified(user_settings, "settings")
        session.add(user_settings)

        logger.debug(f"Expected cloths type - {clothes_type}")
        image_to_show = session.exec(next_image_stmt).first()

        if image_to_show:
            return image_to_show
        else:
            logger.debug(
                f"No more images with cloths type - {clothes_type} and image type - {image_type}"
            )
            logger.debug(f"Trying to find new cloths type for image type - {image_type}")
            # Altering the cloths type. Look for the cloths type with the most photos and current image type left
            next_cloths_result = session.exec(next_image_subquery).first()

    if next_cloths_result:
        new_cloths_type = next_cloths_result[0]
        logger.debug(f"New cloths type successfully founded - {new_cloths_type}")

        user_settings.settings[key_image_clothes_type_from_settings] = new_cloths_type
        flag_modified(user_settings, "settings")
        session.add(user_settings)

        next_image_stmt = (
            select(ImageInfo)
            .where(
                ImageInfo.character == char_id,
                ImageInfo.cloths == new_cloths_type,
                ImageInfo.rating == image_type,
                ImageInfo.is_free == False,
                ImageInfo.id.not_in(user_viewed_images_subquery),
                ImageInfo.config_id == config_id,
            )
            .order_by(func.random())
            .limit(1)
        )
        image_to_show = session.exec(next_image_stmt).first()

        if image_to_show:
            return image_to_show
        else:
            logger.debug(f"No more altering images {clothes_type}, {image_type}")
            raise NoImagesException("No images found for the next location!!!!!")

    # altering the image_type Hot → Sexy → Sensual → Photo
    # TODO: replace naive approach with querying of the next available image type
    #       starting from requested_image_type and up
    logger.debug(f"The following type of clothing could not be found for image type - {image_type}")
    logger.debug("Altering image type")
    allowed_image_types_stmt = (
        select(ImageInfo.rating)
        .where(
            ImageInfo.id.not_in(user_viewed_images_subquery),
            ImageInfo.character == char_id,
            ImageInfo.config_id == config_id,
            ImageInfo.rating.not_in(["defect", "double"]),  # Добавляем явный фильтр
        )
        .group_by(ImageInfo.rating)
    )
    allowed_images_types = session.exec(allowed_image_types_stmt).all()

    image_type_pos = IMAGE_TYPES.index(image_type)
    if image_type_pos > 0:
        new_image_type = IMAGE_TYPES[image_type_pos - 1]
    else:
        raise AllImagesAreShownException("All images have been shown for you!")

    status = True
    logger.debug(f"{allowed_images_types=}")
    while status:
        if new_image_type in allowed_images_types:
            logger.debug(f"{new_image_type=}")
            break
        image_type_pos = IMAGE_TYPES.index(new_image_type)
        if image_type_pos > 0:
            new_image_type = IMAGE_TYPES[image_type_pos - 1]
        else:
            raise AllImagesAreShownException("All images have been shown for you!")

    key_image_clothes_type_from_settings = SETTINGS_IMAGE_CLOTHES_TYPE_KEY.format(
        image_type=new_image_type
    )
    if key_image_clothes_type_from_settings in user_settings.settings:
        new_cloths_type: str = user_settings.settings[key_image_clothes_type_from_settings]
        logger.debug(
            f"Found cloths type - {new_cloths_type} for new image type - {new_image_type} at user settings"
        )
    else:
        next_image_subquery = (
            select(ImageInfo.cloths, func.count(ImageInfo.id).label("photo_count"))
            .where(
                ImageInfo.id.not_in(user_viewed_images_subquery),
                ImageInfo.rating == new_image_type,
                ImageInfo.is_free == False,
                ImageInfo.character == char_id,
                ImageInfo.config_id == config_id,
            )
            .group_by(ImageInfo.cloths)
            .order_by(func.count(ImageInfo.id).desc())
            .limit(1)
        )
        next_cloths_type = session.exec(next_image_subquery).first()

        new_cloths_type = next_cloths_type[0]
        logger.debug(f"Found cloths type - {new_cloths_type} for new image type - {new_image_type}")
        user_settings.settings[key_image_clothes_type_from_settings] = new_cloths_type
        flag_modified(user_settings, "settings")
        session.add(user_settings)

    next_image_stmt = (
        select(ImageInfo)
        .where(
            ImageInfo.character == char_id,
            ImageInfo.cloths == new_cloths_type,
            ImageInfo.rating == new_image_type,
            ImageInfo.is_free == False,
            ImageInfo.id.not_in(user_viewed_images_subquery),
            ImageInfo.config_id == config_id,
        )
        .order_by(func.random())
        .limit(1)
    )
    image_to_show = session.exec(next_image_stmt).first()

    # Check case if we don't have the cloths type that entered at settings, if we don't -> trying to alter cloths type
    if image_to_show:
        return image_to_show
    else:
        logger.debug(
            f"No more images with cloths type - {clothes_type} and image type - {image_type}"
        )
        logger.debug(f"Altering the cloths type for image type - {image_type}")
        next_image_subquery = (
            select(ImageInfo.cloths, func.count(ImageInfo.id).label("photo_count"))
            .where(
                ImageInfo.id.not_in(user_viewed_images_subquery),
                ImageInfo.rating == new_image_type,
                ImageInfo.is_free == False,
                ImageInfo.character == char_id,
                ImageInfo.config_id == config_id,
            )
            .group_by(ImageInfo.cloths)
            .order_by(func.count(ImageInfo.id).desc())
            .limit(1)
        )
        next_cloths_type = session.exec(next_image_subquery).first()

        new_cloths_type = next_cloths_type[0]
        logger.debug(f"Found cloths type - {new_cloths_type} for new image type - {new_image_type}")
        user_settings.settings[key_image_clothes_type_from_settings] = new_cloths_type
        flag_modified(user_settings, "settings")
        session.add(user_settings)

    next_image_stmt = (
        select(ImageInfo)
        .where(
            ImageInfo.character == char_id,
            ImageInfo.cloths == new_cloths_type,
            ImageInfo.rating == new_image_type,
            ImageInfo.is_free == False,
            ImageInfo.id.not_in(user_viewed_images_subquery),
            ImageInfo.config_id == config_id,
        )
        .order_by(func.random())
        .limit(1)
    )
    image_to_show = session.exec(next_image_stmt).first()

    if image_to_show:
        return image_to_show
    else:
        raise Exception("No images found for the next image type!!!!!")


def mark_image_as_seen(session, user_id, image_id):
    user_view = UserImageView(user_id=user_id, image_id=image_id)
    session.add(user_view)
    return user_view


def reset_images_user(session: Session, user_id: uuid.UUID):
    session.execute(delete(UserImageView).where(UserImageView.user_id == user_id))
    session.execute(delete(ImagesUserSettings).where(ImagesUserSettings.id == user_id))


async def process_image_getting(
    session: Session,
    user_id: uuid.UUID,
    char_id: int,
    image: ImageInfo,
    config_id: Optional[uuid.UUID] = None,
) -> MessageDTO:
    # Use late import to avoid circular dependency
    from . import messages

    # params = {"user_id": user_id, "image_id": image.id, "char_id": char_id}
    # captions_service = LLMServiceAPI(
    #     api_url=config.caption_service_url.__str__(),
    #     api_key=config.llm_services_api_key.get_secret_value(),
    # )
    # caption_response: ImageCaptionResponse = await captions_service.get(
    #     params=params, validation_schema=ImageCaptionResponse
    # )
    # # Check that we have success response
    # if not caption_response:
    #     caption = ""
    # else:
    #     caption = caption_response.caption
    #     if not caption:
    #         caption = ""
    # записать сообщение в базу
    message = messages.send_message(
        session,
        char_id,
        user_id,
        "character",
        "",
        LLMStats.dummy(),
        [{"type": "image", "id": image.id.hex}],
        message_type=ChatMessageType.DEFAULT_IMAGE,
        config_id=config_id,
    )
    # пометить картинку как просмотренную
    mark_image_as_seen(session, user_id, image.id)

    return MessageDTO(MessageType.IMAGE, message, image)
