create table "content"."message_archive" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default now(),
    "text" text,
    "attachments" jsonb,
    "user_id" uuid,
    "char_id" integer,
    "channel_id" bigint
);


CREATE UNIQUE INDEX message_archive_pkey ON content.message_archive USING btree (id);

alter table "content"."message_archive" add constraint "message_archive_pkey" PRIMARY KEY using index "message_archive_pkey";


