alter table "content"."llm_stats" drop constraint "content_llm_stats_message_id_fkey";

create table "content"."summaries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "channel_id" bigint not null,
    "summary" text not null,
    "message_date_from" timestamp with time zone not null,
    "message_date_to" timestamp with time zone not null
);


alter table "content"."llm_stats" drop column "message_id";

alter table "content"."llm_stats" add column "ref_id" integer not null;

alter table "content"."llm_stats" add column "ref_type" text not null;

alter table "content"."llm_stats" add column "user_id" uuid not null;

CREATE UNIQUE INDEX summaries_pkey ON content.summaries USING btree (id);

alter table "content"."summaries" add constraint "summaries_pkey" PRIMARY KEY using index "summaries_pkey";

alter table "content"."summaries" add constraint "content_summaries_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE not valid;

alter table "content"."summaries" validate constraint "content_summaries_channel_id_fkey";


