create table "content"."llm_stats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message_id" bigint,
    "model_id" character varying not null,
    "model_latency" integer not null,
    "input_tokens" integer not null,
    "output_tokens" integer not null
);


CREATE UNIQUE INDEX llm_stats_pkey ON content.llm_stats USING btree (id);

alter table "content"."llm_stats" add constraint "llm_stats_pkey" PRIMARY KEY using index "llm_stats_pkey";

alter table "content"."llm_stats" add constraint "content_llm_stats_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public.messages(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "content"."llm_stats" validate constraint "content_llm_stats_message_id_fkey";


