alter table "content"."user_plans" add column "is_paid" boolean;
create table "content"."clearings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


CREATE UNIQUE INDEX clearings_pkey ON content.clearings USING btree (id);

alter table "content"."clearings" add constraint "clearings_pkey" PRIMARY KEY using index "clearings_pkey";

ALTER TABLE content.transactions
ADD COLUMN clearing_id BIGINT DEFAULT NULL,
ADD CONSTRAINT fk_clearing FOREIGN KEY (clearing_id) REFERENCES content.clearings ("id");
INSERT INTO content.balances (id, currency_type_id, is_official) VALUES
(331924282, 1, true);

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$DECLARE
    -- Declare variables
    company_trial_tokens_balance_id INTEGER := 572450034;
    trial_tokens INTEGER := 5;
    user_token_balance_id INTEGER;
    first_transaction_id UUID;
    second_transaction_id UUID;
BEGIN
    -- Generate UUIDs for correlation IDs
    first_transaction_id := gen_random_uuid();
    second_transaction_id := gen_random_uuid();

    -- Log the start of the function
    -- INSERT INTO auth.trigger_log(action) VALUES ('Trigger fired with new id: ' || NEW.id);

    -- Perform the insert into the users table
    INSERT INTO public.users (id, tg_id)
    VALUES (NEW.id, 123);

    -- Log successful insert
    -- INSERT INTO auth.trigger_log(action) VALUES ('Successfully inserted new id: ' || NEW.id);

    -- Insert the user into the 'Trial' tariff plan
    INSERT INTO content.user_plans (user_id, tariff_plan_id)
    VALUES (NEW.id, (SELECT id FROM content.tariff_plans WHERE is_trial = true and is_archived = false));

    -- 1. Insert balance for "TOKEN" with balance_amount = trial_tokens
    INSERT INTO content.balances (user_id, balance_amount, currency_type_id)
    VALUES (NEW.id, trial_tokens, (SELECT id FROM content.currency_types WHERE name = 'TOKEN'))
    RETURNING id INTO user_token_balance_id;

    -- 2. Insert balance for "SERVICE" with balance_amount = 0
    INSERT INTO content.balances (user_id, balance_amount, currency_type_id)
    VALUES (NEW.id, 0, (SELECT id FROM content.currency_types WHERE name = 'SERVICE'));

    -- 3. Insert balance for "USD" with balance_amount = 0
    INSERT INTO content.balances (user_id, balance_amount, currency_type_id)
    VALUES (NEW.id, 0, (SELECT id FROM content.currency_types WHERE name = 'EUR'));

    -- 4. Decrease company trial token balance by trial_tokens
    UPDATE content.balances
    SET balance_amount = balance_amount - trial_tokens
    WHERE id = company_trial_tokens_balance_id;

    -- 5. Insert records into the transactions table
    INSERT INTO content.transactions (id, balance_id_from, balance_id_to, amount, transaction_type, user_id, correlation_id)
    VALUES (first_transaction_id, company_trial_tokens_balance_id, user_token_balance_id, -trial_tokens, 'BALANCE_WITHDRAW', NEW.id, second_transaction_id);

    INSERT INTO content.transactions (id, balance_id_from, balance_id_to, amount, transaction_type, user_id, correlation_id)
    VALUES (second_transaction_id, user_token_balance_id, company_trial_tokens_balance_id, trial_tokens, 'BALANCE_TOP_UP', NEW.id, first_transaction_id);

    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        -- Log the error
        RAISE EXCEPTION 'Error in handle_new_user: % | Role: % | User: %', SQLERRM, current_role, session_user;
END;$function$
;
