create table "content"."content_character_images" (
    "id" bigint generated by default as identity not null,
    "character_id" integer not null,
    "image_id" uuid not null
);


CREATE UNIQUE INDEX content_character_images_pkey ON content.content_character_images USING btree (id);

alter table "content"."content_character_images" add constraint "content_character_images_pkey" PRIMARY KEY using index "content_character_images_pkey";

alter table "content"."content_character_images" add constraint "content_character_images_character_id_fkey" FOREIGN KEY (character_id) REFERENCES content.content_characters(id) ON DELETE CASCADE not valid;

alter table "content"."content_character_images" validate constraint "content_character_images_character_id_fkey";

alter table "content"."content_character_images" add constraint "content_character_images_image_id_fkey" FOREIGN KEY (image_id) REFERENCES content.content_images(id) ON DELETE CASCADE not valid;

alter table "content"."content_character_images" validate constraint "content_character_images_image_id_fkey";

drop view if exists "public"."characters";

CREATE OR REPLACE VIEW "public"."characters" AS
WITH trait_agg AS (
    SELECT ctc.content_characters_id,
        array_remove(array_agg(DISTINCT ct.name), NULL::character varying) AS traits
    FROM content.content_traits_content_characters ctc
    JOIN content.content_traits ct ON ctc.content_traits_id = ct.id
    GROUP BY ctc.content_characters_id
), filter_agg AS (
    SELECT cfc.content_characters_id,
        array_remove(array_agg(DISTINCT cf.name), NULL::character varying) AS filters
    FROM content.content_character_filters_content_characters cfc
    JOIN content.content_character_filters cf ON cfc.content_character_filters_id = cf.id
    GROUP BY cfc.content_characters_id
), location_agg AS (
    SELECT clc.content_characters_id,
        array_remove(array_agg(DISTINCT cl.name), NULL::character varying) AS locations
    FROM content.content_locations_content_characters clc
    JOIN content.content_locations cl ON clc.content_locations_id = cl.id
    GROUP BY clc.content_characters_id
), additional_files_agg AS (
    SELECT ccf.content_characters_id,
        array_remove(array_agg(DISTINCT df2.filename_disk), NULL::character varying) AS additional_files
    FROM content.content_characters_files ccf
    JOIN content.directus_files df2 ON ccf.directus_files_id = df2.id
    GROUP BY ccf.content_characters_id
), profile_images_agg AS (
    SELECT cci.character_id,
        array_agg(cci.image_id) AS profile_images_ids
    FROM content.content_character_images cci
    GROUP BY cci.character_id
)
SELECT cc.id,
    cc.status,
    cc.sort,
    cc.name,
    cc.public_description,
    COALESCE(t.traits, '{}'::character varying[]) AS traits,
    COALESCE(f.filters, '{}'::character varying[]) AS filters,
    COALESCE(l.locations, '{}'::character varying[]) AS locations,
    df.filename_disk AS main_photo,
    COALESCE(a.additional_files, '{}'::character varying[]) AS profile_images,
    COALESCE(p.profile_images_ids, '{}'::uuid[]) AS profile_images_ids
FROM content.content_characters cc
LEFT JOIN trait_agg t ON cc.id = t.content_characters_id
LEFT JOIN filter_agg f ON cc.id = f.content_characters_id
LEFT JOIN location_agg l ON cc.id = l.content_characters_id
LEFT JOIN content.directus_files df ON cc.main_photo = df.id
LEFT JOIN additional_files_agg a ON cc.id = a.content_characters_id
LEFT JOIN profile_images_agg p ON cc.id = p.character_id;

alter table "content"."content_images" add column "is_free" BOOLEAN NOT NULL DEFAULT false;