create table "content"."content_banners" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "button_text" text not null,
    "button_url" text not null,
    "number" smallint,
    "subscript" text,
    "number_text" text,
    "is_active" boolean not null default false
);


CREATE UNIQUE INDEX content_banners_pkey ON content.content_banners USING btree (id);

alter table "content"."content_banners" add constraint "content_banners_pkey" PRIMARY KEY using index "content_banners_pkey";

alter table "content"."paid_actions" add column "is_public" boolean not null default false;

create or replace view "public"."paid_actions" as  SELECT paid_actions.id,
    paid_actions.price,
    paid_actions.description
   FROM content.paid_actions
  WHERE ((paid_actions.is_archived = false) AND (paid_actions.is_public = true));



