create type public.user_status as enum ('ONLINE', 'OFFLINE');

drop table if exists public.users;

-- Step 3: Create the users table with the status column referencing the user_status enum
create table public.users (
  id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, -- UUID from auth.users
  display_name text,
  status      public.user_status default 'OFFLINE',
  tg_id       text
);


comment on table public.users is 'Profile data for each user.';

create table public.channels (
    id bigint generated by default as identity primary key,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references public.users(id) on delete cascade,
    char_id int references content.content_characters on delete cascade,
    UNIQUE(user_id, char_id)
);

comment on table public.channels is 'Message channels';
-- MESSAGES

drop table if exists public.messages;
create table public.messages (
        id bigint generated by default as identity primary key,
        inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
        text text,
        attachments jsonb,
        user_id uuid references public.users on DELETE CASCADE,
        char_id int references content.content_characters on DELETE CASCADE,
        channel_id bigint references public.channels on delete cascade not null
    );
comment on table public.messages is 'Individual messages.';

alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;

ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;
create policy "Allow read access to channels " on public.channels for select
using (auth.uid() = user_id);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read access to messages" ON public.messages FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.channels c
            WHERE c.id = public.messages.channel_id
                AND c.user_id = auth.uid()
        )
    );

-- Send "previous data" on change 
alter table public.users replica identity full; 
alter table public.channels replica identity full; 
alter table public.messages replica identity full;

-- inserts a row into public.users and assigns roles
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id)
  values (new.id);  
  return new;
end;
$$ language plpgsql security definer set search_path = auth, public;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

begin; 
  -- remove the realtime publication
  drop publication if exists supabase_realtime; 

  -- re-create the publication but don't enable it for any tables
  create publication supabase_realtime;  
commit;

-- add tables to the publication
alter publication supabase_realtime add table public.channels;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.users;
