create table "content"."currency_types" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    constraint "currency_types_pkey" primary key ("id"),
    constraint "currency_types_name_key" unique ("name")
);
create table "content"."balances" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "currency_type_id" bigint,
    "balance_amount" numeric default '0'::numeric,
    constraint "balances_pkey" primary key ("id"),
    constraint "balances_currency_type_id_fkey" foreign key ("currency_type_id") 
        references "content"."currency_types" ("id") 
        on delete set null not valid
);
create table "content"."paid_actions" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "price" numeric not null,
    "is_archived" boolean not null default false,
    constraint "paid_actions_pkey" primary key ("id")
);
create table "content"."tariff_plans" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "tokens_per_month" numeric,
    "duration_in_month" smallint,
    "currency_type_id" bigint,
    "month_price" numeric,
    "is_trial" boolean not null default false,
    "is_archived" boolean not null default false,
    "tariff_info" text[],
    constraint "tariff_plans_pkey" primary key ("id"),
    constraint "tariff_plans_currency_type_id_fkey" foreign key ("currency_type_id") 
        references "content"."currency_types" ("id") 
        on delete set null not valid
);
create table "content"."token_batches" (
    "id" bigint generated by default as identity not null,
    "token_amount" numeric not null,
    "user_stats_id" uuid,
    "expiration_date" timestamp with time zone DEFAULT null,
    constraint "token_batches_pkey" primary key ("id")
);
create table "content"."token_packs" (
    "id" uuid not null default gen_random_uuid(),
    "amount" numeric not null,
    "currency_type_id" bigint,
    "price" numeric not null,
    "is_archived" boolean not null default false,
    constraint "token_packs_pkey" primary key ("id"),
    constraint "token_packs_currency_type_id_fkey" foreign key ("currency_type_id") 
        references "content"."currency_types" ("id") 
        on delete set null not valid
);
create table "content"."transactions" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "balance_id_from" bigint not null,
    "balance_id_to" bigint not null,
    "transaction_type" text not null,
    "service_id" uuid,
    "amount" numeric,
    "source_name" text not null,
    "additional_data" json,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    constraint "transactions_pkey" primary key ("id")
);
create table "public"."user_stats" (
    "user_id" uuid not null default gen_random_uuid(),
    "tariff_plan_id" uuid,
    "expired_at" timestamp with time zone default NULL,
    constraint "user_stats_pkey" primary key ("user_id"),
    constraint "user_stats_tariff_plan_id_fkey" foreign key ("tariff_plan_id") 
        references "content"."tariff_plans" ("id") 
        on delete set null not valid
);
alter table "public"."user_stats" enable row level security;
alter table "content"."token_batches"
add constraint "token_batches_user_stats_id_fkey"
foreign key ("user_stats_id") 
references "public"."user_stats" ("user_id") 
on delete set null not valid;
grant all on table "public"."user_stats" to "anon", "authenticated", "service_role"