create table "content"."gift_codes" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "token_amount" integer,
    "code_type" text,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);
alter table "content"."gift_codes" add column "tokens_lifetime_hours" integer not null default 48;


create table "content"."gift_codes_users" (
    "id" bigint generated by default as identity not null,
    "gift_code_id" uuid default gen_random_uuid(),
    "user_id" uuid default gen_random_uuid(),
    "activated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


CREATE UNIQUE INDEX gift_codes_pkey ON content.gift_codes USING btree (id);

CREATE UNIQUE INDEX gift_codes_users_pkey ON content.gift_codes_users USING btree (id);

alter table "content"."gift_codes" add constraint "gift_codes_pkey" PRIMARY KEY using index "gift_codes_pkey";

alter table "content"."gift_codes_users" add constraint "gift_codes_users_pkey" PRIMARY KEY using index "gift_codes_users_pkey";

alter table "content"."gift_codes_users" add constraint "gift_codes_users_gift_code_id_fkey" FOREIGN KEY (gift_code_id) REFERENCES content.gift_codes(id) ON DELETE CASCADE not valid;

alter table "content"."gift_codes_users" validate constraint "gift_codes_users_gift_code_id_fkey";

alter table "content"."gift_codes_users" add constraint "gift_codes_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "content"."gift_codes_users" validate constraint "gift_codes_users_user_id_fkey";



CREATE UNIQUE INDEX gift_codes_code_key ON content.gift_codes USING btree (code);

alter table "content"."gift_codes" add constraint "gift_codes_code_key" UNIQUE using index "gift_codes_code_key";


