GET http://localhost:8000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Ik5mWnk4MldsbWxHOWFwa0MiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE3MDA4OTg3LCJpYXQiOjE3MTcwMDUzODcsImlzcyI6Imh0dHBzOi8vbmt4Y3JwZndwbXFtbmlvdm12cW4uc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjI1ODdlMzU4LTc3ZWMtNDVkMS05OGRjLTJjZWUxMzUyNmI3NCIsImVtYWlsIjoiMTMwODIyNTE4NUB0Zy5mbGlydGVsbG8uY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6IjEzMDgyMjUxODVAdGcuZmxpcnRlbGxvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIyNTg3ZTM1OC03N2VjLTQ1ZDEtOThkYy0yY2VlMTM1MjZiNzQifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcxNzAwNTM4N31dLCJzZXNzaW9uX2lkIjoiMzNjZjBlY2MtMzY4Yy00NjMxLWJlNTgtMWNjNDZhNTg1YjAxIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.ze6q1E6zFx-2L6x_ZNch8Kv5z86agwaL0EycFsJR-aA